package com.example.foos

import com.example.foos.ui.home.PostItemUiState

object Posts {
    fun getPosts(): List<PostItemUiState> {
        return listOf(
            PostItemUiState(
                "userid",
                "username1",
                "id",
                "content",
                listOf()
            ),
            PostItemUiState(
                "userid",
                "username2",
                "id",
                "content",
                listOf()
            ),
            PostItemUiState(
                "userid",
                "username3",
                "id",
                "content",
                listOf()
            ),
            PostItemUiState(
                "userid",
                "username4",
                "id",
                "content",
                listOf()
            ),
            PostItemUiState(
                "userid",
                "username5",
                "id",
                "content",
                listOf()
            ),
            PostItemUiState(
                "userid",
                "username6",
                "id",
                "content",
                listOf()
            ),
            PostItemUiState(
                "userid",
                "username7",
                "id",
                "content",
                listOf()
            ),
            PostItemUiState(
                "userid",
                "username8",
                "id",
                "content",
                listOf()
            ),
            PostItemUiState(
                "userid",
                "username9",
                "id",
                "content",
                listOf()
            ),
            PostItemUiState(
                "userid",
                "username10",
                "id",
                "content",
                listOf()
            ),
        )
    }
}